apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awser-aks-ninja-dev-06
  namespace: ns-awser
  labels:
    type: application
spec:
  project: p-awser
  source:
    repoURL: https://github.com/jonasnorlund/aks-platform-tenants
    targetRevision: HEAD
    path: verify
  destination:
    name: aks-ninja-dev-06
    namespace: ns-awser
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
