apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-awser
  namespace: ns-awser
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-awser
  storageClassName: azurefile-csi
