apiVersion: v1
kind: Secret
metadata:
  name: repo-REPLACE
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: REPLACE
  password: REPLACE
  username: admin
  project: default