apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: REPLACE
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  mountOptions:
    - dir_mode=0777  
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict  
    - nosharesock  
    - actimeo=30  
    - nobrl  
  csi:
    driver: file.csi.azure.com
    volumeHandle: REPLACE
    volumeAttributes:
      shareName: REPLACE  
      storageAccount: REPLACE
      resourceGroup: REPLACE
      mountWithManagedIdentity: "true"
      clientID: REPLACE
